--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MANTENIMIENTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MANTENIMIENTOS" 
   (	"ID_MANTENIMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(*,2), 
	"CREADO_EL" VARCHAR2(20 BYTE), 
	"ID_TIENDA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MANTENIMIENTOS
SET DEFINE OFF;
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('2','CAMBIO ACEITE','55000','03/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('3','ENGRASE','35000','03/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('41','ARREGLO SUSPENSIÓN','350000','04/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('42','CAMBIO BUGÍAS','280000','04/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('43','CAMBIO LLANTAS','100000','04/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('44','ARREGLO CHASÍS','400000','04/03/21','40');
Insert into SYSTEM.MANTENIMIENTOS (ID_MANTENIMIENTO,NOMBRE,PRECIO,CREADO_EL,ID_TIENDA) values ('45','CAMBIO BATERÍA','100000','04/03/21','40');
--------------------------------------------------------
--  DDL for Index MANTENIMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MANTENIMIENTOS_PK" ON "SYSTEM"."MANTENIMIENTOS" ("ID_MANTENIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MANTENIMIENTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" MODIFY ("ID_MANTENIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" MODIFY ("ID_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" ADD CONSTRAINT "MANTENIMIENTOS_PK" PRIMARY KEY ("ID_MANTENIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANTENIMIENTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MANTENIMIENTOS" ADD CONSTRAINT "MANTENIMIENTOS_FK1" FOREIGN KEY ("ID_TIENDA")
	  REFERENCES "SYSTEM"."TIENDAS" ("ID_TIENDA") ENABLE;
