--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPUESTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REPUESTOS" 
   (	"ID_REPUESTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(*,2), 
	"CANTIDAD" NUMBER, 
	"CREADO_EL" DATE, 
	"ID_TIENDA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.REPUESTOS
SET DEFINE OFF;
Insert into SYSTEM.REPUESTOS (ID_REPUESTO,NOMBRE,PRECIO,CANTIDAD,CREADO_EL,ID_TIENDA) values ('1','ACEITE AAA','1500000','47',to_date('03/03/21','DD/MM/RR'),'40');
Insert into SYSTEM.REPUESTOS (ID_REPUESTO,NOMBRE,PRECIO,CANTIDAD,CREADO_EL,ID_TIENDA) values ('21','BATERÍA','450000','12',to_date('04/03/21','DD/MM/RR'),'40');
Insert into SYSTEM.REPUESTOS (ID_REPUESTO,NOMBRE,PRECIO,CANTIDAD,CREADO_EL,ID_TIENDA) values ('22','BUGÍAS','2000000','12',to_date('04/03/21','DD/MM/RR'),'40');
--------------------------------------------------------
--  DDL for Index INVENTARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INVENTARIO_PK" ON "SYSTEM"."REPUESTOS" ("ID_REPUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPUESTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("ID_REPUESTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPUESTOS" ADD CONSTRAINT "INVENTARIO_PK" PRIMARY KEY ("ID_REPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPUESTOS" MODIFY ("ID_TIENDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPUESTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPUESTOS" ADD CONSTRAINT "INVENTARIO_FK1" FOREIGN KEY ("ID_TIENDA")
	  REFERENCES "SYSTEM"."TIENDAS" ("ID_TIENDA") ENABLE;
