--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SOLICITUDES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SOLICITUDES" 
   (	"ID_SOLICITUD" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"ID_VEHICULO" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"CREADO_EL" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SOLICITUDES
SET DEFINE OFF;
Insert into SYSTEM.SOLICITUDES (ID_SOLICITUD,DESCRIPCION,ID_VEHICULO,ESTADO,CREADO_EL) values ('1','Hola, mi vehiculo tiene un escape en el líquido para frenos, quisiera que por favor lo resivsaran','43','COMPLETADA',to_date('04/03/21','DD/MM/RR'));
Insert into SYSTEM.SOLICITUDES (ID_SOLICITUD,DESCRIPCION,ID_VEHICULO,ESTADO,CREADO_EL) values ('2','reparacion de prueba que necesito','45','COMPLETADA',to_date('04/03/21','DD/MM/RR'));
Insert into SYSTEM.SOLICITUDES (ID_SOLICITUD,DESCRIPCION,ID_VEHICULO,ESTADO,CREADO_EL) values ('3','Solicitud de prueba 3','43','INCOMPLETA',to_date('04/03/21','DD/MM/RR'));
Insert into SYSTEM.SOLICITUDES (ID_SOLICITUD,DESCRIPCION,ID_VEHICULO,ESTADO,CREADO_EL) values ('4','Reparación de llantas','61','INCOMPLETA',to_date('04/03/21','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SOLICITUDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SOLICITUDES_PK" ON "SYSTEM"."SOLICITUDES" ("ID_SOLICITUD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SOLICITUDES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SOLICITUDES" MODIFY ("ID_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SOLICITUDES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SOLICITUDES" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SOLICITUDES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SOLICITUDES" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SOLICITUDES" ADD CONSTRAINT "SOLICITUDES_PK" PRIMARY KEY ("ID_SOLICITUD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOLICITUDES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SOLICITUDES" ADD CONSTRAINT "SOLICITUDES_FK1" FOREIGN KEY ("ID_VEHICULO")
	  REFERENCES "SYSTEM"."VEHICULOS" ("ID_VEHICULO") ENABLE;
