--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIENDAS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIENDAS" 
   (	"ID_TIENDA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"CREADO_EL" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TIENDAS
SET DEFINE OFF;
Insert into SYSTEM.TIENDAS (ID_TIENDA,NOMBRE,DIRECCION,ESTADO,CREADO_EL) values ('1','SODIMAC 1','CALLE 1 #2C-31','ACTIVA',to_date('20/02/21','DD/MM/RR'));
Insert into SYSTEM.TIENDAS (ID_TIENDA,NOMBRE,DIRECCION,ESTADO,CREADO_EL) values ('2','SODIMAC 2','CALLE 2 #2C-32','ACTIVA',to_date('03/03/21','DD/MM/RR'));
Insert into SYSTEM.TIENDAS (ID_TIENDA,NOMBRE,DIRECCION,ESTADO,CREADO_EL) values ('40','SODIMAC 3','CALLE 3 #2C-33','ACTIVA',to_date('03/03/21','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index TIENDAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIENDAS_PK" ON "SYSTEM"."TIENDAS" ("ID_TIENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIENDAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIENDAS" MODIFY ("ID_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIENDAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIENDAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIENDAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIENDAS" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIENDAS" ADD CONSTRAINT "TIENDAS_PK" PRIMARY KEY ("ID_TIENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
