--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VEHICULOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VEHICULOS" 
   (	"ID_VEHICULO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MARCA" VARCHAR2(20 BYTE), 
	"MODELO" VARCHAR2(20 BYTE), 
	"MODELO_FECHA" VARCHAR2(20 BYTE), 
	"PLACA" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"FOTO_1" VARCHAR2(255 BYTE), 
	"FOTO_2" VARCHAR2(255 BYTE), 
	"CREADO_EL" DATE, 
	"ID_CLIENTE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.VEHICULOS
SET DEFINE OFF;
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('2','MAZDA','MAZDA 3','2019','WTK-123','ROJO',null,null,to_date('03/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('42','Chevrolet','Aveo','2019','WTG-123','Verde',null,null,to_date('04/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('43','Renault','Clio','2009','abc-123','Gris',null,null,to_date('04/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('44','Renault','Clio','2008','abd-534','Azul',null,null,to_date('04/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('45','Bugati','abc','2007','mjk-123','Verde',null,null,to_date('04/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('46','Mazda','3','2005','asd-123','Gris',null,null,to_date('04/03/21','DD/MM/RR'),'6');
Insert into SYSTEM.VEHICULOS (ID_VEHICULO,MARCA,MODELO,MODELO_FECHA,PLACA,COLOR,FOTO_1,FOTO_2,CREADO_EL,ID_CLIENTE) values ('61','Suzuki','Gixxer','2020','hjk-123','Rosa',null,null,to_date('04/03/21','DD/MM/RR'),'22');
--------------------------------------------------------
--  DDL for Index VEHICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VEHICULOS_PK" ON "SYSTEM"."VEHICULOS" ("ID_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VEHICULOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("MODELO_FECHA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULOS" ADD CONSTRAINT "VEHICULOS_PK" PRIMARY KEY ("ID_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VEHICULOS" ADD CONSTRAINT "VEHICULOS_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SYSTEM"."CLIENTES" ("ID_CLIENTE") ENABLE;
